# Generated by Django 6.0 on 2025-12-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('owner', 'Hostel Owner'), ('mess_owner', 'Mess Owner'), ('admin', 'Admin')], db_index=True, default='user', max_length=20),
        ),
    ]
