# Generated by Django 6.0 on 2025-12-29 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.PositiveIntegerField()),
                ('area_name', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Delivery Area',
                'verbose_name_plural': 'Delivery Areas',
                'ordering': ['area_name'],
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Homes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=1000, upload_to='home/')),
                ('alt_text', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mess.home')),
            ],
            options={
                'verbose_name': 'Home Image',
                'verbose_name_plural': 'Home Images',
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.PositiveIntegerField()),
                ('plan_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meals', models.PositiveIntegerField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Meal Plan',
                'verbose_name_plural': 'Meal Plans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], db_index=True, max_length=10)),
                ('veg_breakfast', models.CharField(blank=True, max_length=150, null=True)),
                ('veg_breakfast_accompaniment', models.CharField(blank=True, max_length=150, null=True)),
                ('veg_lunch', models.CharField(blank=True, max_length=150, null=True)),
                ('veg_lunch_accompaniment', models.CharField(blank=True, max_length=150, null=True)),
                ('veg_dinner', models.CharField(blank=True, max_length=150, null=True)),
                ('veg_dinner_accompaniment', models.CharField(blank=True, max_length=150, null=True)),
                ('nonveg_breakfast', models.CharField(blank=True, max_length=150, null=True)),
                ('nonveg_breakfast_accompaniment', models.CharField(blank=True, max_length=150, null=True)),
                ('nonveg_lunch', models.CharField(blank=True, max_length=150, null=True)),
                ('nonveg_lunch_accompaniment', models.CharField(blank=True, max_length=150, null=True)),
                ('nonveg_dinner', models.CharField(blank=True, max_length=150, null=True)),
                ('nonveg_dinner_accompaniment', models.CharField(blank=True, max_length=150, null=True)),
                ('breakfast_image', models.ImageField(blank=True, null=True, upload_to='mess_menu/breakfast/')),
                ('lunch_image', models.ImageField(blank=True, null=True, upload_to='mess_menu/lunch/')),
                ('dinner_image', models.ImageField(blank=True, null=True, upload_to='mess_menu/dinner/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='ProviderFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.PositiveIntegerField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Provider Feature',
                'verbose_name_plural': 'Provider Features',
                'ordering': ['title'],
            },
        ),
        migrations.AddIndex(
            model_name='home',
            index=models.Index(fields=['city', 'state'], name='mess_home_city_1bf000_idx'),
        ),
        migrations.AddIndex(
            model_name='home',
            index=models.Index(fields=['owner', 'is_verified'], name='mess_home_owner_i_d85243_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['provider_type', 'provider_id'], name='mess_mealpl_provide_3c1cdb_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['name'], name='mess_mealpl_name_ca01ec_idx'),
        ),
        migrations.AddIndex(
            model_name='messmenu',
            index=models.Index(fields=['content_type', 'object_id'], name='mess_messme_content_d7da94_idx'),
        ),
        migrations.AddIndex(
            model_name='messmenu',
            index=models.Index(fields=['day'], name='mess_messme_day_453ebd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messmenu',
            unique_together={('content_type', 'object_id', 'day')},
        ),
    ]
