# Generated by Django 6.0 on 2025-12-29 13:05

import django.db.models.deletion
import hostels.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Hostel Facility',
                'verbose_name_plural': 'Hostel Facilities',
            },
        ),
        migrations.CreateModel(
            name='HostelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=hostels.models.hostel_image_upload_path)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_cover', models.BooleanField(default=False, help_text='Primary image for hostel listing')),
                ('order', models.PositiveIntegerField(default=0, help_text='Image display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hostel Image',
                'verbose_name_plural': 'Hostel Images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostelRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rule_type', models.CharField(choices=[('general', 'General'), ('safety', 'Safety'), ('timings', 'Timings'), ('behavior', 'Behavior')], db_index=True, default='general', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text="Deactivated rules won't be shown to users")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hostel Rule',
                'verbose_name_plural': 'Hostel Rules',
                'ordering': ['hostel', 'rule_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('pincode', models.CharField(db_index=True, max_length=10)),
                ('hostel_type', models.CharField(choices=[('gents', 'Gents'), ('ladies', 'Ladies'), ('mixed', 'Mixed')], db_index=True, default='mixed', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
