# Generated by Django 6.0 on 2025-12-29 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostels', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelfacility',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_facilities', to='rooms.facility'),
        ),
        migrations.AddField(
            model_name='hostelfacility',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_facilities', to='hostels.hostel'),
        ),
        migrations.AddField(
            model_name='hostelimage',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hostels.hostel'),
        ),
        migrations.AddField(
            model_name='hostelrule',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='hostels.hostel'),
        ),
        migrations.AddIndex(
            model_name='hostel',
            index=models.Index(fields=['city', 'state'], name='hostels_hos_city_05fe4f_idx'),
        ),
        migrations.AddIndex(
            model_name='hostel',
            index=models.Index(fields=['hostel_type'], name='hostels_hos_hostel__c5a501_idx'),
        ),
        migrations.AddIndex(
            model_name='hostel',
            index=models.Index(fields=['owner', 'is_verified'], name='hostels_hos_owner_i_8f1e94_idx'),
        ),
        migrations.AddConstraint(
            model_name='hostelfacility',
            constraint=models.UniqueConstraint(fields=('hostel', 'facility'), name='unique_hostel_facility'),
        ),
        migrations.AddIndex(
            model_name='hostelimage',
            index=models.Index(fields=['hostel', 'is_cover'], name='hostels_hos_hostel__6193a2_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelrule',
            index=models.Index(fields=['hostel', 'rule_type'], name='hostels_hos_hostel__9b5634_idx'),
        ),
    ]
