# Generated by Django 6.0 on 2025-12-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='available_rooms_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='hostel',
            name='total_rooms_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
